services:
  mysql1:
    image: mysql:latest
    container_name: mysql1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql1
    networks:
      - spring-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=rootpassword || exit 1"]
      interval: 10s
      retries: 5

  spring-app:
    image: meriem01/tp-foyer:5.0.0
    container_name: spring-app
    ports:
      - "8089:8089"
    depends_on:
      mysql1:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - spring-network

volumes:
  mysql-data:

networks:
  spring-network:
