
services:
  mysql1:
    image: mysql:latest
    container_name: mysql1
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - mysql-data:/var/lib/mysql1

  spring-app:
    image: meriem01/tp-foyer:5.0.0
    container_name: spring-app
    ports:
      - "8089:8089"
    depends_on:
       - mysql1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql1:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: unless-stopped

volumes:
  mysql-data:
